### ISSUE TITLE
While receiving data, user is unable to scroll back chatBox

### ISSUE THREAD

**Issue by chrishow** [mrdjohnson/llm-x#26]
Hi!

Firstly, this is a great PWA! Awesome to be able to use this offline!

I notice that while receiving data, the user isn't able to scroll backwards. There's a `!overflow-y-hidden` class [added to the scrollableFeed](https://github.com/mrdjohnson/llm-x/blob/a86012d0f146b7f2745f8f51b9e3557d4f1e5231/src/containers/ChatBox.tsx#L73) in the chatBox container.

It would (IMO) be useful if the user could scroll the scrollableFeed while Ollama is 'thinking' or generating tokens. 

I was thinking of working on this, but wanted to check if this was a design choice.

**Comment by mrdjohnson** [comment]
First off, thanks for using the app!

It's both intentional and unwanted, there was A LOT of weirdness around scrolling while getting a message but only scrolling if the user was already at the bottom 😵‍💫
Eventually I gave up and forced the scroll.

I haven't looked into it since then but if you can set it up for it to scroll correctly that would be awesome. Otherwise we can just add a "toggle scroll" field in the settings

**Comment by mrdjohnson** [comment]
👋 hey! Wanted to follow up and confirm you wanted to take a crack at this? I'd be happy to answer any questions

**Comment by mrdjohnson** [comment]
How to test: 
- remove the  the `scrollIntoView` prop on the IncomingMessage in Message.tsx
- remove addition to the ChatBox.tsx classname that hides the overflow during an incoming message
- put your viewport in a mobile state and use a fast / small model
- ask the model to output a couple paragraphs about anything
- (optional): add a function that outputs true to the `changeDetectionFilter` for react-scrollable-feed. but also put in a console log saying it detected changes


For me this consistently showed that the changeDetection functionality did not even know to trigger

**Comment by mrdjohnson** [comment]
changing the message key in `ChatBox.tsx` to be the content (forcing the change to detect) also does not make it scroll.

sigh

**Comment by mrdjohnson** [comment]
I put out a stopgap fix for now! Users are able to scroll while getting messages (the change was actually needed when I added it support for concurrent models)

**Comment by chrishow** [comment]
Sorry for the radio silence, I'm still being crushed at work 😰

Glad you found a fix, I will try it out as soon as I get some free time!
