### ISSUE TITLE
UI issue: "Go to section"

### ISSUE THREAD

**Issue by neuhaus** [mrdjohnson/llm-x#29]
The "Go to section" button in the UI (that opens the menu) doesn't look like something you should tap, so it's not very intuitive. (on mobile safari)

Solution: Make it look more like a button. Perhaps by adding something like 🔽 after the name? (like a bit further down on the page next to "Dracula")

Also the color of the menu button is almost the same as the background color so you can't really see its shape.

**Comment by mrdjohnson** [comment]
Any and all mobile suggestions are Soo welcomed 😅

I don't like "Go to section" either. Feels/sounds weird.

**Comment by mrdjohnson** [comment]
Pushing an update for this now, switched it to a nextui dropdown instead
