### ISSUE TITLE
UI issue: adding a model 

### ISSUE THREAD

**Issue by neuhaus** [mrdjohnson/llm-x#31]
When adding a model, it's very unintuitive that the list of possible models doesn't disappear and you get to edit the model that you just added.

Right now the steps are like this instead (on desktop):

 1. click on the gear icon
 2. click on models on the left
 3. click "Add new connection" at the bottom
 4. click on "Ollama" (for example)
 5. click on the X in the top right corner
 6. click on the gear icon
 7. click on models on the left
 8. click on the "edit" icon to the right of the model you added in step 4
 9. edit the settings 

With my suggestion it would go straight from step 4 to step 9.

This is also an issue on mobile safari.

**Comment by mrdjohnson** [comment]
This will be fixed (for web) on the next update. 

It'll come in a later chrome extension update. Thank You for the find!
