### ISSUE TITLE
UI Issue: Theme list cannot be opened on mobile safari

### ISSUE THREAD

**Issue by neuhaus** [mrdjohnson/llm-x#33]
On mobile safari (iPhone), when i go to the general settings and tap on "Dracula" (the default theme name), or the "V" next to it, nothing happens.

On desktop i can click on the "V" next to it (not on the name, unfortunately) and a list of themes appears.

I suggest you change it so you can also click on the name to open the list.

Also i suggest you do not pick "Dracula" as the default theme because of its low contrast.

**Comment by mrdjohnson** [comment]
Whoa, I just tried it on an iphone and it doesn't do anything!!! Why?! Strange. 

I think that's a daisy UI bug, I'll look into it thank you!

**Comment by mrdjohnson** [comment]
I found the issue and eventually, switched the ui to use nextui instead of daisyui; This will be fixed in the next update!

also "Dracula" was a personal preference. I realized I actively like this theme and want it to be the "intro" theme people see when they come to the app.
