### ISSUE TITLE
Mid-generation unexpected non-whitespace 

### ISSUE THREAD

**Issue by DipFlip** [mrdjohnson/llm-x#5]
Sometimes during generation of a response I get the error below. Have not been able to reproduce it reliably but seems to be more often when generating code.

```
Unexpected non-whitespace character after JSON at position 132 (line 2 column 1)

SyntaxError: Unexpected non-whitespace character after JSON at position 132 (line 2 column 1)
at JSON.parse (<anonymous>)
at OllmaApi.streamChat (https://localhost:5173/llm-x/src/utils/OllamaApi.ts:46:25)
at async Object.generateMessage (https://localhost:5173/llm-x/src/models/ChatModel.ts:113:24)
```

![image](https://github.com/mrdjohnson/llm-x/assets/12473575/098a765b-ce10-4a0f-9c06-8ad4b10d969e)

**Comment by mrdjohnson** [comment]
I think I have seen this once before. Maybe I need to trip the response before parsing it. 

I'll check on this soon, thanks for reporting!
