### ISSUE TITLE
build fails on Windows

### ISSUE THREAD

**Issue by DipFlip** [mrdjohnson/llm-x#6]
On Windows, running `npm run dev` fails with 

```
> llm-x@0.8.0 dev
> npm run remove-dev-dist && DEBUG=vite-plugin-pwa SW_DEV=true vite --force


> llm-x@0.8.0 remove-dev-dist
> rm -rf dev-dist

'rm' is not recognized as an internal or external command,
operable program or batch file.
```

**Comment by mrdjohnson** [comment]
@DipFlip can you confirm that the above branch works for you?

**Comment by DipFlip** [comment]
Woa you're too fast xD ! 

The next (and last) issue that pops up then is 

```'DEBUG' is not recognized as an internal or external command,```

which I fixed in [this](https://github.com/mrdjohnson/llm-x/pull/8) PR using `cross-env`
